# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.java.home=C:/Users/leonm/.jdks/jbr-17.0.9
org.gradle.daemon=false

# Mod Properties
mod_version=1.1.1
mod_group=invmod
mod_name=invasion

# Minecraft & NeoForge Versions
minecraft_version=1.19.2
neoforge_version=43.3.0

# Optional Parchment Mappings
# Enable if you want better parameter names
#neogradle.subsystems.parchment.minecraftVersion=1.19.2
#neogradle.subsystems.parchment.mappingsVersion=2022.08.14

mc_version=1.12.2
mcp_mappings=snapshot_20171003